image: python:2.7

stages:
 - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "~/.platformio"

before_script:
  - "pip install -U platformio"



build:
  stage: build
  needs: []
  script: 
    - pio run